Compiler/urls.py
__author__ = "Harshit"

from django.conf.urls import url, include
from rest_framework import routers
from django.views.generic import TemplateView
import apiviews
import views

urlpatterns = [

    url(r'^compiler$', TemplateView.as_view(template_name='Compiler/compiler_try.html')),
    url(r'^progList$',views.ProgramListView.as_view(), name='progs_list'),
    url(r'^progList/(?P<pk>[0-9]+)$',views.ProgramDetailView.as_view()),
    url(r'^addProg$',views.ProgramCreate.as_view()),
    url(r'^results',TemplateView.as_view(template_name='Compiler/results.html')),
    url(r'^progList/time/(?P<pk>[0-9]+)$',apiviews.getTimer),
    url(r'^api/start/(?P<pk>[0-9]+)$', apiviews.startTimer),
    url(r'^api/compile', apiviews.compile),
    url(r'^api/run', apiviews.run),
    url(r'^api/submit',apiviews.submit),
    url(r'^api/results',apiviews.results),

]

HashitCompiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^hashitCompile/',include('Compiler.urls')),
    url('^', include('django.contrib.auth.urls')),
                  url(r'^accounts/', include('registration.backends.simple.urls')),
                  # url(r'^login/$', 'django.contrib.auth.views.login'),
    # url(r'^logout/$', 'django.contrib.auth.views.logout'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Compiler/models.py
__author__ = "Harshit"

from django.db import models
from django.contrib.auth.models import User
import os



class Tests(models.Model):
    test_name = models.CharField(max_length=20)
    prog_input = models.CharField(max_length=1000)
    output = models.CharField(max_length=1000)

    def __str__(self):
        return self.test_name


class Problem(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=1000)
    difficulty = models.CharField(max_length=20)
    tests = models.ManyToManyField(Tests)

    def __str__(self):
        return self.title


class TimerProblem(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Problem)
    # time_init = models.TimeField(auto_now_add=True)
    time_init = models.DateTimeField(auto_now_add=True)

class Solution(models.Model):
    # submission_name = models.CharField(max_length=50)

    question = models.ForeignKey(Problem)
    user = models.ForeignKey(User)
    program = models.CharField(max_length=2000)
    # output = models.CharField(max_length=1000)
    submission_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.submission_name

Compiler/forms.py
from django.contrib import admin

__author__ = "Harshit"

from django import forms
from models import *

class CabModelForm( forms.ModelForm ):
    description = forms.CharField(widget=forms.Textarea)
    # title = forms.CharField(widget=forms.TextInput)
    # difficulty = forms.CharField(widget=forms.TextInput)




    class Meta:
        fields = ['title', 'description', 'difficulty', 'tests']
        model = Problem

class Cab_Admin( admin.ModelAdmin ):
    form = CabModelForm

Compiler/views.py
__author__ = "Harshit"

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from Compiler.models import  *
from django import forms
from django.forms.extras.widgets import SelectDateWidget

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@method_decorator(login_required, name='dispatch')
class ProgramListView(ListView):
    model = Problem
    context_object_name = 'progs'

@method_decorator(login_required, name='dispatch')
class ProgramCreate(CreateView):
    model = Problem
    fields = ['title','description','difficulty']

    def get_success_url(self):
        return reverse('progs_list')

@method_decorator(login_required, name='dispatch')
class ProgramDetailView(DetailView):
    model = Problem
    context_object_name = 'problem'

templates/Compiler/compiler_try.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
<p id="output3"></p><br>
<p id="errors"></p>
<form  id="compileForm" method="POST" >
    {% csrf_token %}
    <div class="form-group">
	Prog Name :<input name='prog_name' >
	<select name='language'>

		<option value="C">C</option>
		<option value="Java">Java</option>
	</select>
	<br>
	<textarea name='program' id='program' rows="30" cols="100"></textarea>
    <textarea name='prog_input' id='prog_input' rows="10" cols="20"></textarea>
	<br>
        </div>
    <input name="prog_type" id="prog_type" hidden>
    <button type="submit" class="btn btn-primary" onclick="javascript:compile1()" name="compile" >Compile</button>
    <button type="submit" class="btn btn-primary" onclick="javascript:run1()" name="run" >Run</button>
{#    #}
{#    #}
</form>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.js"></script>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

<script>
    var signup_options = {
        target:        '#output3',   // target element(s) to be updated with server response
        beforeSubmit:  showRequest,  // pre-submit callback
        success:       successful,  // post-submit callback
         error : dispError

            };


    function compile1() {
{#        $('#compileForm').action ='http://127.0.0.1:8000/posts/api/compile';#}
{#        this.action = 'http://127.0.0.1:8000/posts/api/compile';#}
        $('#prog_type').val('compile');
        return true;
    }
    function run1(){
{#     $('#compileForm').action ='http://127.0.0.1:8000/posts/api/run';#}
{#        this.action = 'http://127.0.0.1:8000/posts/api/run';#}
        $('#prog_type').val('run');
        return true;
    }
    $('#compileForm').submit(function(){
            $(this).ajaxSubmit(signup_options);

         return false;
     });
    function  dispError() {
        $('#errors').html('Encountered errors');
    }
    function showRequest(formData, jqForm, options) {

        if($('#prog_type').val()=='compile')
                options.url ='http://127.0.0.1:8000/hashitCompile/api/compile';
        else if($('#prog_type').val()=='run')
                options.url = 'http://127.0.0.1:8000/hashitCompile/api/run';

        return true;
    }
    function  successful(responseText, statusText, xhr, $form) {
        if(responseText.typeOp=='compile') {
            if (responseText.compiled == true) {
                $('#errors').html('');
                $('#output3').html("<i class='fa fa-check-circle' style=\"font-size:48px;color:green\"></i>");
                $('#output3').append(" Successfully Compiled<br>");

            } else {
                $('#output3').html('');
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:48px;color:red\"></i>Compilation Erros<br>" + responseText.errors);
            }
        }else if(responseText.typeOp=='run'){
            if(responseText.executed == true) {
                $('#output3').html("<i class='fa fa-check-circle' style=\"font-size:48px;color:green\"></i>Ran successfully");
                $('#output3').html("<h3>Output<\/h3><br>"+responseText.output);
                $('#errors').html('');
            }else if(responseText.compiled==false){
                $('#output3').html('');
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:48px;color:red\"></i>Compile the file first<br>" );
            }else{
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:48px;color:red\"></i>Time Limit Exceeded<br>" );
            }
        }

        return false;
    }
</script>

</body>
</html>

templates/Compiler/problem_detail.html
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
	<title>{{ problem.title }}</title>

    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation-flex.css" />

    <style type="text/css" media="screen">
        h4,h5,p,a,.time{
            font-family: 'Ubuntu', sans-serif;

        }
    #editor {
        position: absolute; /* Added */
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
   }
</style>

</head>
<body>

<nav class = "navbar navbar-inverse" role = "navigation">

   <div class = "navbar-header">
      <a class = "navbar-brand" href = "#">Hashit Compile</a>
   </div>

   <div>
      <ul class = "nav navbar-nav">
         <li class ><a href = "#">ingenuITy</a></li>
         <li><a href = "#">IDE</a></li>

         <li><a href = "#">Contest</a></li>

      </ul>
   </div>

</nav>

<span class="success label"><h4>{{ problem.title }}</h4></span>
<h5>Time Elapsed :<div class="time"></div></h5>
    {{  problem.description| linebreaks }}
<div class="jumbotron"><h4>Problem Statement</h4>
{#{% autoescape on %}#}


{#{% endautoescape %}#}
    </div>
<div class="callout primary"><p id="output3"></p><br>
<p id="errors"></p>
    </div>
<form  id="compileForm" method="POST" >
    {% csrf_token %}
    <div class="form-group">
	Prog Name :<input name='prog_name' >
	<select name='language'>

		<option value="C">C</option>
		<option value="Java">Java</option>
	</select>
	<br>
        <div width="75%">
        <textarea name='program' id='program' rows="30" cols="100" hidden ></textarea>
    <textarea name='program1' id='program1' rows="30" cols="100" ></textarea>
        </div>
        <h5>Input</h5>
    <textarea name='prog_input' id='prog_input' ></textarea>
	<br>
        </div>
    <input name="prob" id="prob" hidden value='{{ problem.id }}'>
    <input name="prog_type" id="prog_type" hidden>
{#    <button type="submit" class="btn btn-primary" onclick="javascript:compile1()" name="compile" >Compile</button>#}
{#    <button type="submit" class="btn btn-primary" onclick="javascript:run1()" name="run" >Run</button>#}
{#    <button type="submit" class="btn btn-primary" onclick="javascript:submit1()" name="submit" >Submit</button>#}
    <button type="submit" style="font-family: 'Ubuntu', sans-serif;" class="warning button" onclick="javascript:save1()" name="compile" >Save</button>
     <button type="submit" style="font-family: 'Ubuntu', sans-serif;" class="warning button" onclick="javascript:compile1()" name="compile" >Compile</button>
    <button type="submit" style="font-family: 'Ubuntu', sans-serif;" class="button" onclick="javascript:run1()" name="run" >Run</button>
    <button type="submit"  style="font-family: 'Ubuntu', sans-serif;" class="success button" onclick="javascript:submit1()" name="submit" >Submit</button>
{#    #}
{#    #}
</form>

<form  id="timerForm" method="POST" action="time/{{ problem.id }}">
    {% csrf_token %}
    <input name="prob" id="prob" hidden value='{{ problem.id }}'>
    </form>
{#<h4>Test Cases</h4>#}
{#<p>#}
{#    {% for area in problem.tests.all %}{{ area.prog_input }}<br/>{% endfor %}#}
{#</p>#}


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.js"></script>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ace.js"></script>
<script>
    var editor = ace.edit("program1");


    editor.setTheme("ace/theme/monokai");

    editor.setOptions({
    maxLines: 15,
        fontSize: "15px",
{#        fontFamily: 'Ubuntu'#}
});
    editor.getSession().setMode("ace/mode/c_cpp");

{#    document.getElementsByClassName('ace')[0].style.fontSize='15px';#}

{#    hljs.highlightBlock()#}
    var signup_options = {
{#        target:        '#output3',   // target element(s) to be updated with server response#}
        beforeSubmit:  showRequest,  // pre-submit callback
        success:       successful,  // post-submit callback
         error : dispError

            };

    var load_options = {
{#        target:        '#output3',   // target element(s) to be updated with server response#}
        beforeSubmit:  showRequest,  // pre-submit callback
        success:       timerFn,  // post-submit callback
         error : dispError

            };

    $(document).ready(function() {

{#            var str =$('#pd').val();#}
{#            str.replace("\n","&#10");#}
{#            $('#pd').val(str);#}

            $('#timerForm').submit(function(){
            $(this).ajaxSubmit(load_options);

         return false;
        });

            $('#timerForm').submit();
    });
    var startTime =0;

    function display(){
         var endTime = new Date();

        var timeDiff = endTime - startTime;

          timeDiff /= 1000;

    // get seconds
    var seconds = Math.round(timeDiff % 60);

    // remove seconds from the date
    timeDiff = Math.floor(timeDiff / 60);

    // get minutes
    var minutes = Math.round(timeDiff % 60);

    // remove minutes from the date
    timeDiff = Math.floor(timeDiff / 60);

    // get hours
    var hours = Math.round(timeDiff % 24);

    // remove hours from the date
    timeDiff = Math.floor(timeDiff / 24);

    // the rest of timeDiff is number of days
    var days = timeDiff;

    $(".time").text( hours + ":" + minutes + ":" + seconds);
    setTimeout(display, 1000);
    }
    function timerFn(responseText, statusText, xhr, $form){

{#        var hr = responseText.hr;#}
{#        var min = responseText.min;#}
{#        var sec = responseText.sec;#}

        var endTime = new Date();
{##}
{#        hr = endTime.getHours() - hr;#}
{#        min = endTime.getMinutes() - min;#}
{#        sec = endTime.getSeconds() - sec;#}
{##}
{#        $(".time").text( hr + ":" + min + ":" + sec);#}
{#        setTimeout(display, 1000);#}

            startTime = responseText.tt;
          var timeDiff = endTime - responseText.tt;

          timeDiff /= 1000;

    // get seconds
    var seconds = Math.round(timeDiff % 60);

    // remove seconds from the date
    timeDiff = Math.floor(timeDiff / 60);

    // get minutes
    var minutes = Math.round(timeDiff % 60);

    // remove minutes from the date
    timeDiff = Math.floor(timeDiff / 60);

    // get hours
    var hours = Math.round(timeDiff % 24);

    // remove hours from the date
    timeDiff = Math.floor(timeDiff / 24);

    // the rest of timeDiff is number of days
    var days = timeDiff;

    $(".time").text( hours + ":" + minutes + ":" + seconds);
    setTimeout(display, 1000);
    }

    function compile1() {
{#        $('#compileForm').action ='http://127.0.0.1:8000/posts/api/compile';#}
{#        this.action = 'http://127.0.0.1:8000/posts/api/compile';#}
        $('#prog_type').val('compile');
        return true;
    }
    function submit1() {
{#        $('#compileForm').action ='http://127.0.0.1:8000/posts/api/compile';#}
{#        this.action = 'http://127.0.0.1:8000/posts/api/compile';#}
        $('#prog_type').val('submit');
        return true;
    }
    function run1(){
{#     $('#compileForm').action ='http://127.0.0.1:8000/posts/api/run';#}
{#        this.action = 'http://127.0.0.1:8000/posts/api/run';#}
        $('#prog_type').val('run');
        return true;
    }
    $('#compileForm').submit(function(){
            $(this).ajaxSubmit(signup_options);

         return false;
     });
    function  dispError() {
        $('#errors').html('Encountered errors');
    }
    function showRequest(formData, jqForm, options) {
{#        var text = $('.ace_text-layer').text();#}
        var text = "";
        $('.ace_text-layer>div').each(function(){ console.log("item "); text += '\n' + this.innerText; });

        $('#program').val(text);

        if($('#prog_type').val()=='compile')
                options.url ='http://127.0.0.1:8000/hashitCompile/api/compile';
        else if($('#prog_type').val()=='run')
                options.url = 'http://127.0.0.1:8000/hashitCompile/api/run';
        else if($('#prog_type').val()=='submit')
                options.url = 'http://127.0.0.1:8000/hashitCompile/api/submit';

        return true;
    }
    function  successful(responseText, statusText, xhr, $form) {
        if(responseText.typeOp=='compile') {
            if (responseText.compiled == true) {
                $('#errors').html('');
                $('#output3').html("<i class='fa fa-check-circle' style=\"font-size:24px;color:green\"></i>");
                $('#output3').append(" Successfully Compiled<br>");

            } else {
                $('#output3').html('');
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:24px;color:red\"></i>Compilation Erros<br>" + responseText.errors);
            }
        }else if(responseText.typeOp=='run'){
            if(responseText.executed == true) {
                $('#output3').html("<i class='fa fa-check-circle' style=\"font-size:24px;color:green\"></i>Ran successfully");
                $('#output3').html("<h3>Output<\/h3><br>"+responseText.output);
                $('#errors').html('');
            }else if(responseText.compiled==false){
                $('#output3').html('');
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:24px;color:red\"></i>Compile the file first<br>" );
            }else{
                $('#errors').html("<i class=\"fa fa-exclamation-triangle\" style=\"font-size:24px;color:orangered\"></i>"+ "Time Limit Exceeded<br>" );
            }
        }else if(responseText.typeOp=='submit'){
            if(responseText.executed == true) {
                $('#output3').html('');
                $('#errors').html('');

                for (t in responseText.cases){
                    if(responseText.cases[t].match) {
                        $('#output3').append("<i class='fa fa-check-circle' style=\"font-size:24px;color:green\"></i>"+ t +'<br>');
                    }else if(responseText.cases[t].executed){
                        $('#errors').append("<i class=\"fa fa-times-circle\" style=\"font-size:24px;color:red\"></i>"+t+" Wrong Answer<br>" );
                    }else{
                        $('#errors').append("<i class=\"fa fa-exclamation-triangle\" style=\"font-size:24px;color:orangered\"></i>"+t+" Time Limit Exceeded<br>" );
                    }
                }

            }
            else if(responseText.compiled==false){
                $('#output3').html('');
                $('#errors').html("<i class=\"fa fa-times-circle\" style=\"font-size:32px;color:red\"></i>Compile the file first<br>" );
            }
        }

        return false;
    }
</script>

</body>
</html>

templates/Compiler/problem_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
<table>
    {{ form.as_table }}
</table>
    <input type="submit" value="Save" />
</form>
</body>
</html>

templates/Compiler/problem_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

	<title>Contest</title>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation-flex.css" />

    <style type="text/css" media="screen">
        h4,h5,p,a{
            font-family: 'Ubuntu', sans-serif;

        }
        </style>

</head>
<body>
<form id="attempt-form" method="POST">
{% csrf_token %}
<div class="panel-body">
<div class="jumbotron" style="background-color: whitesmoke">
	<div class="container">

       <input name="prob_s" id="prob_s" hidden >

        <ol align="center" class="list-group">
        {% for prog  in progs %}
            <li class="list-group-item center-block text-center"><a href="progList/{{ prog.id }}">{{ prog.title }}</a>

<br>
    <button type="submit" style="font-family: 'Ubuntu', sans-serif;" class="button"  name="attempt" onclick="javascript:sendTR({{ prog.id }})" data-prob="{{ prog.id }}" >Attempt</button>
<br>
               {{ prog.timerproblem_set.all }}

        {% endfor %}
    </ol>

    </div>
</div>
	</div>
</form>
<p id="errors"></p>
</body>
</html>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.js"></script>
<script>
    var signup_options = {
{#        target:        '#output3',   // target element(s) to be updated with server response#}
        beforeSubmit:  showRequest,  // pre-submit callback
        success:       successful,  // post-submit callback
         error : dispError

            };

    function  sendTR(prob_id) {
         $('#prob_s').val(prob_id);
        return true;
    }
    function showRequest(formData, jqForm, options) {
{#        var text = $('.ace_text-layer').text();#}

        console.log(formData);
        console.log(jqForm);
        console.log(options);
         options.url ='http://127.0.0.1:8000/hashitCompile/api/start/'+ $('#prob_s').val();
        return true;
    }

    function  successful(responseText, statusText, xhr, $form) {

        console.log(responseText);
        console.log(statusText);
        console.log(xhr);
        console.log($form);
        window.location.href=  window.location.href +'/'+ responseText.id;
    }
    function  dispError() {
        $('#errors').html('Encountered errors');
    }

     $('#attempt-form').submit(function(){
            $(this).ajaxSubmit(signup_options);

         return false;
     });
</script>

templates/Compiler/results.html
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
	<title>{{ problem.title }}</title>

    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation-flex.css" />

    <style type="text/css" media="screen">
        h4,h5,p,a,.time{
            font-family: 'Ubuntu', sans-serif;

        }
    #editor {
        position: absolute; /* Added */
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
   }
</style>

</head>
<body>
<form>

</form>


<script>
    $(document).ready(function() {

            $('#rForm').submit(function(){
            $(this).ajaxSubmit(load_options);

         return false;
        });

            $('#rForm').submit();
    });
 var load_options = {
{#        target:        '#output3',   // target element(s) to be updated with server response#}
        beforeSubmit:  showRequest,  // pre-submit callback
        success:      rFn,  // post-submit callback
         error : dispError

            };

    function  rFn(responseText, statusText, xhr, $form) {

    }
     function showRequest(formData, jqForm, options) {
         return true;
     }
</script>
</body>
</html>

templates/django-registration-templates-master/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Index page
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Index page
{% endblock %}